version: '3.4'

services:
  study_backend:
    image: study_backend
    build: ./
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080

networks:
  nestjs_network:
    driver: bridge
